name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.IP }}
          port: 2222
          username: Jordi
          key: ${{secrets.PRIVATE_KEY}}
          script: |
            cd /var/www/html/Oxyra/
            git reset --hard; git pull
            cd frontend
            npm install
            npm run build
